// cpld_p45_i2s_audio_generator_top.v — top-level module skeleton
// Generated by: make init PROJECT=CPLD_P45_I2S_AUDIO_GENERATOR
// Fill in ports and logic before running make syn.

module cpld_p45_i2s_audio_generator_top (
    //System Ports
    input wire CLK,
    input wire RST,

    //Soft Latching Power Circuit ports
    input wire PSWI,
    output wire PSWO,

    //Piano Interface Buttons/ Status LEDs
    input wire SUS_PEDAL,
    input wire FUNC_BTN,
    output wire ON_LED,
    //...Need ADC interface for Volume Control but leave it out for now
    
    //Memory Interface Ports TBD

    //Switch Matrix Ports - Piano Keys
    input  wire [5:0]  COL_M1_N,  //Columns have an external pull-up resistor, so they read high when no key is pressed
    input  wire [5:0]  COL_M2_N,  //Columns have an external pull-up resistor, so they read high when no key is pressed
    output wire [14:0] ROW_N,     //A row is driven low with a push-pull IO to scan it; when a key is pressed, the corresponding column is pulled low

    //I2S Ports - Digital Audio Amplifier
    output wire I2S_MCLK,
    output wire I2S_BCLK,
    output wire I2S_LRCLK,
    output wire I2S_DOUT
);

    wire        wea_int;
    wire [6:0]  addra_int;
    wire [1:0]  dia_int;

    wire [14:0] row_en_int;
    wire [5:0]  col_in_m1_int;
    wire [5:0]  col_in_m2_int;

    //Pins are active-low; invert to/from the active-high convention used internally
    assign col_in_m1_int = ~COL_M1_N;
    assign col_in_m2_int = ~COL_M2_N;
    assign ROW_N         = ~row_en_int;

    //This scan key controller take about 165 clock cycles to write the 90*2 switches to the dual port ram 
    //Use this info to choose clk frequency later
    scan_keys_controller scan_controller(
        .clk(CLK),
        .rst(RST),
        //top matrix input ports
        .row_en(row_en_int),
        .col_in_m1(col_in_m1_int),
        .col_in_m2(col_in_m2_int),
        //Memory output ports
        .wea(wea_int),
        .addra(addra_int),
        .dia(dia_int)
    );


    //Note: Should have a rst
    dual_port_ram_dual_clock pressed_keys_ram(
        //Port A: Write Domain
        .clka(CLK),
        .wea(wea_int),
        .addra(addra_int),
        .dia(dia_int),
        //Port B: Read Domain
        .clkb(clk),
        .enb(1'b0),
        .addrb(7'd0),
        .doutb()
    );
    
endmodule
