// cpld_p45_i2s_audio_generator_top.v — top-level module skeleton
// Generated by: make init PROJECT=CPLD_P45_I2S_AUDIO_GENERATOR
// Fill in ports and logic before running make syn.

module cpld_p45_i2s_audio_generator_top (
    //System Ports
    input wire clk,
    input wire rst,

    //Soft Latching Power Circuit ports
    input wire PSWI,
    output wire PSWO,

    //Piano Interface Buttons/ Status LEDs
    input wire SUS_PEDAL,
    input wire FUNC_BTN,
    output wire ON_LED,
    //...Need ADC interface for Volume Control but leave it out for now
    
    //Memory Interface Ports TBD

    //Switch Matrix Ports - Piano Keys
    input  wire [5:0]  col_m1_n,  //Columns have an external pull-up resistor, so they read high when no key is pressed
    input  wire [5:0]  col_m2_n,  //Columns have an external pull-up resistor, so they read high when no key is pressed
    output wire [14:0] row_n,     //A row is driven low with a push-pull IO to scan it; when a key is pressed, the corresponding column is pulled low

    //I2S Ports - Digital Audio Amplifier
    output wire i2s_mclk,
    output wire i2s_bclk,
    output wire i2s_lrclk,
    output wire i2s_dout
);

    wire        wea_int;
    wire [6:0]  addra_int;
    wire [1:0]  dia_int;

    wire [14:0] row_en_int;
    wire [5:0]  col_in_m1_int;
    wire [5:0]  col_in_m2_int;

    //Pins are active-low; invert to/from the active-high convention used internally
    assign col_in_m1_int = ~col_m1_n;
    assign col_in_m2_int = ~col_m2_n;
    assign row_n         = ~row_en_int;

    scan_keys_controller scan_controller(
        .clk(clk),
        .rst(rst),
        //top matrix input ports
        .row_en(row_en_int),
        .col_in_m1(col_in_m1_int),
        .col_in_m2(col_in_m2_int),
        //Memory output ports
        .wea(wea_int),
        .addra(addra_int),
        .dia(dia_int)
    );

    dual_port_ram_dual_clock pressed_keys_ram(
        //Port A: Write Domain
        .clka(clk),
        .wea(wea_int),
        .addra(addra_int),
        .dia(dia_int),
        //Port B: Read Domain
        .clkb(clk),
        .enb(1'b0),
        .addrb(7'd0),
        .doutb()
    );
    
endmodule
